### PR TITLE
Fix CRUD for relationships

### LINKED ISSUE #89: Relationships do not check for valid ID from storage
Relationships do not check for valid ID for Persons when adding from the Storage

### PR DESCRIPTION
**Pull request by XKMai**
Resolves #89 
Fixes Relationships to check for ID when reading from the Storage.
Also fixes the corresponding test cases.

### CODE REVIEW

File: src/main/java/seedu/address/model/AddressBook.java [hunk 1]
```diff
@@ -194,6 +203,12 @@ public void removeRelationship(Relationship relationship) {
         relationships.remove(relationship);
     }
 
+    /**
+     * Removes all relationships that involve the person with the given Id.
+     */
+    public void removeIfContainsPerson(Id personId) {
```
Comment (gordontzx) [inline src/main/java/seedu/address/model/AddressBook.java]: Change to removeRelationshipsIfContainsPerson

File: src/main/java/seedu/address/model/Model.java [hunk 2]
```diff
@@ -177,6 +177,11 @@ public interface Model {
      */
     void deleteRelationship(Relationship relationship);
 
+    /**
+     * Removes all relationships that involve the person with the given Id.
+     */
+    void removeIfContainsPerson(Id personId);
```
Comment (gordontzx) [inline src/main/java/seedu/address/model/Model.java]: Change to removeRelationshipsIfContainsPerson.

**Review by gordontzx — CHANGES_REQUESTED** [review]
Resolves comments
