### PR TITLE
Bug fixes, refactoring of color classes and relationship-related methods

### LINKED ISSUE #105: Fix failed add commands incrementing ID
When add tag/person command fails, the IdManager increments ID anyways.

### LINKED ISSUE #114: Fix tag text color being applied before white tinting

### LINKED ISSUE #116: Refactor color classes and relationship-related methods
1. Change TagColor and TextColor to be under the same Color class.
2. Add utility methods in Relationship
3. Add graph utility functions

### PR DESCRIPTION
**Pull request by gordontzx**
Fixes #105, Fixes #114, Resolves #116

Bug fixes:
1. Add commands for Person and Tag that fail checks at the execution stage no longer increment IDs of respective ID managers.
2. For tags, text color computation now uses the white-tinted display color.

Changes:
The below changes should not affect external behavior.
1. Combined `TagColor` and `TextColor` classes into one `Color` class.
2. Added `hasPersonWithId(..)` and `getCounterpartId(..)` in Relationship class. Modified existing code to make use of these methods.
3. Added a GraphUtil class for graph related methods. Add a `getShortestPath(..)` method that `queryLink(..)` in `ModelManager` uses.

### CODE REVIEW

File: src/main/java/seedu/address/commons/util/GraphUtil.java [hunk 1]
```diff
@@ -0,0 +1,77 @@
...
+        requireNonNull(adjList);
+
+        int numOfNodes = adjList.size();
+
+        if (start == end || adjList.isEmpty()) {
+            return List.of();
+        }
+
+        final int noParent = -1;
+
```
Comment (TastyVeggy) [inline src/main/java/seedu/address/commons/util/GraphUtil.java]: Rather than using comments to indicate what each section of code does, can we factor those sections in to individual private method to improve readability and adherence to SLAP?

File: src/test/java/seedu/address/model/relationship/RelationshipTest.java [hunk 2]
```diff
@@ -52,6 +53,26 @@ public void isSameRelationship() {
         assertFalse(ONE_TWO.isSameRelationship(editedRelationship));
     }
 
+    @Test
+    public void containsRelationShip_notContained_returnsFalse() {
```
Comment (TastyVeggy) [inline src/test/java/seedu/address/model/relationship/RelationshipTest.java]: Is `RelationShip` suppposed to be `Relationship`?

**Review by TastyVeggy — COMMENTED** [review]
To adopt the framework taught in CS2101,

**Prefix criticism with what was done well**: I think some efforts to refactor graph logic into a graphutil class is good for scalability and maintainability!

**Criticisms**: But I think more SLAP can be applied as suggested. I think that the PR title is also quite vague (After 2 months, no one will remember what *some refactoring* refers to.

**End with you have done a great job!**: But it is a step in the right direction! Keep up the good work!

File: src/test/java/seedu/address/model/relationship/RelationshipTest.java (hunk 2 above)
Comment (gordontzx) [reply src/test/java/seedu/address/model/relationship/RelationshipTest.java]: good catch

**Review by adityagk753 — APPROVED** [review]
Interesting use of BFS.

File: src/main/java/seedu/address/commons/util/GraphUtil.java [hunk 3]
```diff
@@ -0,0 +1,77 @@
...
+ * Contains utility methods for graph-related features.
+ */
+public class GraphUtil {
+    /**
+     * Returns the shortest path from {@code start} to {@code end}.
+     * Assumes 0 <= {@code start}, {@code end} < adjList.size().
+     * @param adjList graph to traverse.
+     * @param start starting node index.
+     * @param end ending node index.
+     * @return The shortest path from the starting node the ending node using indices denoted by {@code adjList}.
```
[the remark this answers is not in the document]
Comment (adityagk753) [reply src/main/java/seedu/address/commons/util/GraphUtil.java]: May be inefficient to run BFS for multiple queries. May want to consider using some kind of caching to store past computed results, but probably an overkill for this tP haha.

File: src/main/java/seedu/address/commons/util/GraphUtil.java (hunk 1 above)
Comment (MinhMXC) [reply src/main/java/seedu/address/commons/util/GraphUtil.java]: There are two types of programmer: (1) those who complains about best practices and (2) those who gets work done. Which one are you?
