### PR TITLE
Fix and Enhance current UI, improve code quality

### LINKED ISSUE #109: Improve code quality, add defensive codes
Closes #104

### LINKED ISSUE #113: Relationship UI does not update when Person name changes
Editing a person’s name does not change it in the Relationship UI immediately. A re-render must be triggered for it to load a new name.

### PR DESCRIPTION
**Pull request by yuntaeseo**
Fixed misalignment of no relationship case. 
Enhanced UI view of relationship list. 

Added asserts and defensive programming for my commits. 

Closes #109 #104 

Fixed #113

### CODE REVIEW

File: src/main/java/seedu/address/ui/PersonListPanel.java [hunk 1]
```diff
@@ -31,7 +33,14 @@ public PersonListPanel(ObservableList<Person> personList,
             ObservableList<Tag> tagList,
             ObservableList<Relationship> relationshipList,
             ObservableList<Person> allPersons) {
+
         super(FXML);
+
+        requireNonNull(personList);
+        requireNonNull(tagList);
+        requireNonNull(relationshipList);
+        requireNonNull(allPersons);
```
Comment (gordontzx) [inline src/main/java/seedu/address/ui/PersonListPanel.java]: I think there is a requireAllNonNull method

Comment (yuntaeseo) [reply src/main/java/seedu/address/ui/PersonListPanel.java]: fixed
