### PR TITLE
Branch fix alpha bugs

### LINKED ISSUE #128: Add Relationship can allow adding to self
A User can add a Relationship of a Person to themselves.

### LINKED ISSUE #130: Add Relationship accepts an empty description
Addrel accepts an empty relationship, with d/       being an acceptable input.

### LINKED ISSUE #133: Unused listrel command included
'listrel' command which is to output entire relationship lists is still accepted by ListRelationshipCommand

### LINKED ISSUE #134: Change the delete/edit relationship command format to not accept index
editrel INDEX [p1/CONNECTION_1] [p2/CONNECTION_2] [d/DESCRIPTION]

Instead of index, accepts p1, p2 for search.

### LINKED ISSUE #141: Relationship query error message mismastch
Image

Currently, listrel is taking up error messages. 
Has to refractor prefixes of error messages two relationship queries.

### LINKED ISSUE #145: Help Command should give a summary
The help command may be better for more experienced users to instead give a summary of the commands we have instead of just linking our user guide.

### LINKED ISSUE #147: UserGuide not updated for latest relationship commands
The User Guide has not been updated for the latest commands regarding relationship.

### LINKED ISSUE #149: Remove functionality to list all relationships
The command to list all relationships using `listrel` is no longer in use, it can be deleted.

### PR DESCRIPTION
**Pull request by XKMai**
Fixes #149, Fixes #133
Unused List command has been removed

Fixes #128
addrel now checks that p1 and p2 are not the same person

Fixes #130
addrel should now give a default description

Fixes #134 
editrel and deleterel will now find the relationship to edit/delete via p1 and p2

Fixes #145
Help command now gives a summary of commands for experienced users.

Fixes #147
UG now updated with latest relationship commands including the summary.

Fixes #141 
listrel command message now matches current listrel

### CODE REVIEW

File: src/main/java/seedu/address/logic/commands/ListRelationshipCommand.java [hunk 1]
```diff
@@ -19,31 +18,22 @@ public class ListRelationshipCommand extends Command {
 
     public static final String COMMAND_WORD = "listrel";
 
-    public static final String MESSAGE_USAGE = COMMAND_WORD + ": Lists relationships.\n"
+    public static final String MESSAGE_USAGE = COMMAND_WORD + " p1/ID: Lists relationships related to a connection.\n"
```
Comment (gordontzx) [inline src/main/java/seedu/address/logic/commands/ListRelationshipCommand.java]: the "p1/ID" part can be removed
